"""empty message

Revision ID: 133c70953ed4
Revises: 6b81824e2cb9
Create Date: 2023-04-12 12:08:55.381604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133c70953ed4'
down_revision = '6b81824e2cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
