"""empty message

Revision ID: 677a4e9b4ee6
Revises: 6b1a6b69aba3
Create Date: 2023-04-18 15:45:57.512343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677a4e9b4ee6'
down_revision = '6b1a6b69aba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=400),
               nullable=True)

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('dayofbirth',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dayofbirth',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)

    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.String(length=400),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###
