"""empty message

Revision ID: 9cd3bc36df4b
Revises: def635769cd1
Create Date: 2023-04-11 10:28:45.757788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd3bc36df4b'
down_revision = 'def635769cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('dayofbirth', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dayofbirth')
        batch_op.drop_column('name')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
