"""empty message

Revision ID: ac862ad6bd69
Revises: 9cd3bc36df4b
Create Date: 2023-04-11 17:32:17.473826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac862ad6bd69'
down_revision = '9cd3bc36df4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
